/**
 * Subject Classification Configuration & Constants
 */

export const CLASSIFICATION_CONFIG = {
  /** Confidence >= 0.90 automatically routes to the subject */
  AUTO_ROUTE_THRESHOLD: 0.90,

  /** Confidence 0.75 - 0.89 triggers deeper semantic verification if not already performed */
  VERIFY_THRESHOLD: 0.75,

  /** Confidence < 0.75 requires user confirmation (needs_review) */
  REVIEW_THRESHOLD: 0.75,

  /** Minimum difference between top candidate and runner-up to avoid ambiguous routing */
  MIN_CANDIDATE_MARGIN: 0.10,

  /** Minimum token length for exact keyword matching */
  MIN_TOKEN_LENGTH: 2,

  /** Maximum document sample characters sent to LLM for classification */
  MAX_LLM_SNIPPET_CHARS: 1500,
};

/**
 * Generic academic and single words that MUST NEVER trigger subject routing by themselves.
 * (e.g. "Introduction to Systems.pdf" must not match "Operating Systems" solely on "systems")
 */
export const GENERIC_WORDS_BLACKLIST = new Set([
  'systems',
  'system',
  'engineering',
  'science',
  'management',
  'introduction',
  'intro',
  'design',
  'data',
  'computer',
  'computing',
  'programming',
  'technology',
  'analysis',
  'theory',
  'practical',
  'practicals',
  'lecture',
  'lectures',
  'lec',
  'chapter',
  'chap',
  'ch',
  'notes',
  'note',
  'assignment',
  'assignments',
  'homework',
  'hw',
  'quiz',
  'quizzes',
  'test',
  'exam',
  'examination',
  'midterm',
  'mid',
  'final',
  'finals',
  'paper',
  'papers',
  'lab',
  'laboratory',
  'manual',
  'manuals',
  'guide',
  'guides',
  'tutorial',
  'tut',
  'unit',
  'units',
  'sheet',
  'sheets',
  'task',
  'tasks',
  'project',
  'projects',
  'report',
  'reports',
  'presentation',
  'slides',
  'slide',
  'handout',
  'handouts',
  'study',
  'course',
  'class',
  'module',
  'part',
  'viva',
  'session',
]);

/**
 * Descriptive noise words stripped from filenames during normalization.
 */
export const IGNORE_WORDS = [
  'introduction to',
  'intro to',
  'introduction',
  'intro',
  'theory',
  'practical',
  'practicals',
  'lab',
  'laboratory',
  'manual',
  'notes',
  'note',
  'lecture',
  'lectures',
  'lec',
  'assignment',
  'assignments',
  'quiz',
  'quizzes',
  'mid',
  'midterm',
  'final',
  'finals',
  'chapter',
  'unit',
  'exercise',
  'week',
  'wk',
  'day',
  'session',
  'part',
  'section',
  'module',
];

/**
 * Legacy/Default synonym mappings used as initial seed aliases.
 * These are matched against the user's actual subjects rather than acting as a hardcoded source of truth.
 */
export const DEFAULT_LEGACY_SYNONYMS: Record<string, string[]> = {
  'Parallel Programming': [
    'pp',
    'parallel computing',
    'parallel processing',
    'high performance computing',
    'hpc',
    'openmp',
    'mpi',
    'cuda',
    'multithreading',
  ],
  'Professional Practices': [
    'pp',
    'professional practice',
    'professional ethics',
    'ethics in engineering',
    'engineering ethics',
    'it ethics',
    'ict ethics',
    'professional issues',
    'professional development',
    'it professional',
    'computing ethics',
    'ethics in computing',
  ],
  'Programming Paradigms': [
    'pp',
    'programming paradigm',
    'paradigms',
    'functional programming',
    'paradigm',
  ],
  'Programming Fundamentals': [
    'pf',
    'programming fundamental',
    'computer programming',
    'cp',
    'intro to programming',
    'fundamentals of programming',
  ],
  'Object Oriented Programming': [
    'oop',
    'oops',
    'object oriented',
    'object oriented paradigm',
  ],
  'Database Management Systems': [
    'dbms',
    'db',
    'database',
    'databases',
    'database systems',
    'database management',
    'intro to dbms',
    'introduction to dbms',
    'relational databases',
    'rdbms',
    'sql',
  ],
  'Operating Systems': [
    'os',
    'operating system',
    'intro to os',
    'introduction to os',
    'introduction to operating systems',
    'os concepts',
    'systems programming',
  ],
  'Computer Networks': [
    'cn',
    'networks',
    'computer network',
    'data communication',
    'data communications',
    'data communication and networks',
    'networking',
    'tcp ip',
  ],
  'Software Engineering': [
    'se',
    'software eng',
    'intro to software engineering',
    'introduction to software engineering',
    'software development',
    'software design',
    'sdlc',
  ],
  'Artificial Intelligence': [
    'ai',
    'intro to ai',
    'introduction to ai',
    'artificial intel',
    'computational intelligence',
  ],
  'Machine Learning': [
    'ml',
    'intro to ml',
    'introduction to ml',
    'machine learn',
    'deep learning',
  ],
  'Data Structures': [
    'dsa',
    'ds',
    'data structure',
    'data structures and algorithms',
    'algorithms',
    'algo',
    'data structures & algorithms',
  ],
  'Digital Logic Design': [
    'dld',
    'digital logic',
    'digital design',
    'logic design',
    'digital electronics',
  ],
  'Computer Architecture': [
    'ca',
    'coa',
    'computer organization',
    'comp arch',
    'computer architecture and assembly language',
    'caal',
  ],
  'Theory of Automata': [
    'toa',
    'automata',
    'theory of computation',
    'toc',
    'formal languages',
  ],
  'Human Computer Interaction': [
    'hci',
    'human computer interaction',
    'ui ux',
  ],
  'Web Development': [
    'wd',
    'web dev',
    'web engineering',
    'web tech',
    'web technologies',
  ],
  'Information Security': [
    'is',
    'infosec',
    'cyber security',
    'cybersecurity',
    'network security',
  ],
};

/**
 * Default representative concepts for common academic subjects, used to seed subject profiles.
 */
export const DEFAULT_SUBJECT_CONCEPTS: Record<string, string[]> = {
  'Database Management Systems': [
    'sql',
    'normalization',
    '1nf',
    '2nf',
    '3nf',
    'bcnf',
    'functional dependency',
    'functional dependencies',
    'relational model',
    'relational algebra',
    'er diagram',
    'entity relationship',
    'primary key',
    'foreign key',
    'candidate key',
    'transactions',
    'acid properties',
    'concurrency control',
    'indexing',
    'b tree',
    'database design',
    'query optimization',
    'joins',
  ],
  'Operating Systems': [
    'process',
    'processes',
    'thread',
    'threads',
    'multithreading',
    'scheduling',
    'cpu scheduling',
    'deadlock',
    'deadlocks',
    'semaphore',
    'semaphores',
    'mutex',
    'virtual memory',
    'paging',
    'page replacement',
    'segmentation',
    'file system',
    'fork',
    'context switch',
    'interprocess communication',
    'ipc',
    'kernel',
  ],
  'Computer Networks': [
    'osi model',
    'tcp',
    'udp',
    'ip',
    'ipv4',
    'ipv6',
    'routing',
    'router',
    'switch',
    'packet switching',
    'dns',
    'http',
    'https',
    'lan',
    'wan',
    'subnetting',
    'subnet mask',
    'congestion control',
    'mac address',
    'ethernet',
    'bandwidth',
    'latency',
  ],
  'Software Engineering': [
    'sdlc',
    'agile',
    'scrum',
    'waterfall',
    'requirements engineering',
    'srs',
    'use case',
    'uml',
    'class diagram',
    'sequence diagram',
    'software testing',
    'unit testing',
    'integration testing',
    'design patterns',
    'refactoring',
    'software architecture',
    'git',
    'version control',
    'devops',
  ],
  'Artificial Intelligence': [
    'heuristic search',
    'a* search',
    'minimax',
    'alpha beta pruning',
    'knowledge representation',
    'propositional logic',
    'first order logic',
    'expert systems',
    'fuzzy logic',
    'genetic algorithms',
    'agent',
    'rational agent',
    'state space search',
    'constraint satisfaction',
    'csp',
  ],
  'Machine Learning': [
    'supervised learning',
    'unsupervised learning',
    'linear regression',
    'logistic regression',
    'decision trees',
    'random forest',
    'svm',
    'support vector machines',
    'neural networks',
    'backpropagation',
    'gradient descent',
    'loss function',
    'clustering',
    'k means',
    'overfitting',
    'regularization',
    'cross validation',
  ],
  'Data Structures': [
    'array',
    'arrays',
    'linked list',
    'doubly linked list',
    'stack',
    'queue',
    'circular queue',
    'deque',
    'tree',
    'binary tree',
    'binary search tree',
    'bst',
    'avl tree',
    'red black tree',
    'heap',
    'priority queue',
    'hash table',
    'hashing',
    'graph',
    'bfs',
    'dfs',
    'sorting',
    'quicksort',
    'mergesort',
    'binary search',
    'asymptotic notation',
    'big o',
  ],
  'Digital Logic Design': [
    'logic gates',
    'boolean algebra',
    'karnaugh map',
    'k map',
    'combinational logic',
    'multiplexer',
    'demultiplexer',
    'decoder',
    'encoder',
    'flip flop',
    'sr flip flop',
    'jk flip flop',
    'd flip flop',
    'sequential circuits',
    'registers',
    'counters',
    'finite state machine',
    'fsm',
    'verilog',
    'vhdl',
  ],
  'Parallel Programming': [
    'threads',
    'openmp',
    'mpi',
    'pthreads',
    'cuda',
    'concurrency',
    'parallelism',
    'race condition',
    'critical section',
    'synchronization',
    'gpu',
    'multithreading',
    'fork join',
    'shared memory',
    'distributed memory',
    'barrier',
    'atomic',
    'semaphore',
    'mutex',
    'speedup',
    'amdahl law',
  ],
  'Programming Paradigms': [
    'functional programming',
    'imperative',
    'declarative',
    'object oriented',
    'logic programming',
    'prolog',
    'haskell',
    'scala',
    'lisp',
    'lambda',
    'polymorphism',
    'immutability',
    'pure functions',
    'type inference',
    'monad',
  ],
  'Programming Fundamentals': [
    'variables',
    'data types',
    'loops',
    'arrays',
    'pointers',
    'functions',
    'recursion',
    'conditional statements',
    'control structures',
    'flowchart',
    'pseudocode',
  ],
  'Object Oriented Programming': [
    'classes',
    'objects',
    'inheritance',
    'polymorphism',
    'encapsulation',
    'abstraction',
    'interfaces',
    'constructors',
    'destructors',
    'method overloading',
    'method overriding',
  ],
  'Computer Architecture': [
    'instruction set architecture',
    'isa',
    'mips',
    'risc',
    'cisc',
    'pipeline',
    'pipelining',
    'cache memory',
    'registers',
    'alu',
    'assembly language',
    'branch prediction',
  ],
};
